appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: eP9fe/2lCS98KPvBzdh6vZzlm4Lq2QBWVjMNU1t5ocqQK2m9g2QL8aC/sAfpe4YdeZ1s5BeY5bFxTApF7+1DTuO4MIE3tinRG3iSoJhoaIqeDDX6T2H9i9wEW647MgN3H0Ut/nMydrTqQkzo4TkKJGOzMD6tVUhQwvDAmG7Wk4xo5jm0mVO8w66BoIuuKJSWqrSd083EYB7QxbEyTDh9y8iX0HeNfKsWzgzC94fsSsY9Qf87Xp6yE28lEMrxBJsNFHihqMsAc5jJWkJ+VBkxgs3Tyau8YpzsGic2guHlh16Bwv1C2vSE0aspkcLq+QmUtWfYTc86HmGxWJcQuiXu1juOnXd8j1S40oGXB5IxdtxOBNPIUS5zGTa5k3y+9WG2UMA5TuOvOW+ldDhWWWgZ+Xr+t2hf3BBn/yT5layVKyJ95n2LCiINLSihYiIrX6a+iDLQ8xVQzHN78oB91aNYOr1O/Wm1VjuerCalKnhl2R0gmI+A0kFOQIIVWrgU6HkEVpNQBBmAGH6lIyQLQIlBQRiqhJ0am7KqwZ/6A6gArxonf63Y11exdInjWMiKvWkTmTjpU5gTTUD1OLjYBd4Fsf+KV5KjEphtPcECyzAXT+lEn3LxtQEjGmNrdKml2g4kaPnn7r1bNehNfCuH2aZIUWRnRWdQUZkZDTKo/yBeOIQ=
conda_forge_output_validation: false
